steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/sat-kapita-selekta-b/ks-se-2024-2/672022070-vincent:v.0.1', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'asia-southeast2-docker.pkg.dev/sat-kapita-selekta-b/ks-se-2024-2/672022070-vincent:v.0.1']

  - name: gcr.io/cloud-builders/gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vincent-672022070'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/sat-kapita-selekta-b/ks-se-2024-2/672022070-vincent:v.0.1'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MONGODB_URI=mongodb+srv://vincentexelcio552:mongodb@kapita-tas.5xacj.mongodb.net/,MONGODB_DB=kapita-tas,REDIS_URL=redis://b56e784c-49a7-4adf-be06-7192ca6ea73e@10.85.49.147:6379/0'